name: Wiki

on:
  gollum

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.repository.full_name }}.wiki
          ref: ${{ github.event.pages[0].sha }}
          fetch-depth: 2
      - name: Slack
        run: |
          url=${HTML_URL}/_compare/$(git rev-parse HEAD^)...$(git rev-parse HEAD)
          curl -XPOST ${WEBHOOK_URL} \ 
          -H 'Content-type: application/json' \
          --data @- <<EOS
          {
            "attachments": [
              {
                "color": "#03AF7A",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "Wiki Editier by name.\n\n *Changed Wiki Page*\n Home\n\n *URL*\n http://\n\n *Revision*\n http://"
                    },
                    "accessory": {
                      "type": "image",
                      "image_url": "https://avatars.githubusercontent.com/u/34964162?v=4",
                      "alt_text": "icon"
                    }
                  }
                ]
              }
            ]
          }
          EOS
        env:
          AUTHOER_NAME: ${{ github.actor }}
          AUTHOER_ICON: ${{ github.event.sender.avatar_url }}
          ACTION: ${{ github.event.pages[0].action }}
          TITLE: ${{ github.event.pages[0].title }}
          URL: ${{ github.event.pages[0].html_url }}
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}